### ISSUE TITLE
TypeError parsing parenthesized expression

### ISSUE THREAD

**Issue by mysecretaccount** [khrome/where-parser#1]
Parenthesized expressions don't seem to work properly.  Here is a simple failing example:

(new WhereParser).parse("(a = b) or false");

The execption produced is:
TypeError: Cannot read property 'push' of undefined

**Comment by khrome** [comment]
Confirmed this error, I will look into the cause and commit a fix in the next few days.

Thanks for catching this!

**Comment by khrome** [comment]
There is a bug when the parenthetical is the opening clause. This will work if you try: "a = b or false" or "false or (a = b)" or you can wait for the fix.

**Comment by mysecretaccount** [comment]
Interesting.  Here are a few other failing cases that may or may not reduce to the same bug:

"false or (a=b) or true"
"false or ((a=b) or true)"

**Comment by khrome** [comment]
Awesome, the initial bug is fixed, verifying some other cases, including these.

Thanks again!

**Comment by khrome** [comment]
All cases satisfied, and published to NPM as v0.1.0
